### ISSUE TITLE
location of activemobs bug?

### ISSUE THREAD

**Issue by GreatRaceofGithub** [BerndiVader/mmSkriptAddon#1]
spigot 1.11.2 & MM latest
skript: bensku's fork

https://pastebin.com/ewT6LX2P

It just appears as <none> and it seems that location can not be recorded...
No error.

**Comment by BerndiVader** [comment]
Hello! ```location of {_am}``` will try ot get the location of a bukkit entity/player you need to add activemob and the plugin know to get the location from an activemob. Use this ```location of activemob {_am}``` to get the location from an activemob instance. Also possible: use ```location of entity of activemob {_am}``` to get the location from the entity instance of the activemob. both same same.
