### ISSUE TITLE
Activemob type error after skript-dev37 update

### ISSUE THREAD

**Issue by fl-y** [BerndiVader/mmSkriptAddon#3]
make activemob %activemob% cast skill %string% with trigger %entity% at target %entity%
This used to work fine but shows errors after skript update.
https://imgur.com/a/IGfaatW

**Comment by fl-y** [comment]
![activemob error](https://user-images.githubusercontent.com/31615341/42964203-504ec1a8-8bd1-11e8-871f-06121549d717.PNG)
Adding image because github allows...

**Comment by BerndiVader** [comment]
Hi! Thanks for reporting, but your issue is that you try to use an activemob for the trigger and target. If you want to use the activemob {_am} as trigger & target you need to use its entity instance. Like this: 

```
make activemob {_am} cast skill "Ww_tame" with trigger entity of activemob {_am} at target entity of activemob {_am} 
```

**Comment by fl-y** [comment]
My bad once again.....
I automatically assumed it was the first variable.
Sorry for wasting your time
