### ISSUE TITLE
All other skripts break when installing this addon

### ISSUE THREAD

**Issue by bloggy** [BerndiVader/mmSkriptAddon#6]
Hi there,
hopefully you can help me. I installed your plugin but on server start I get lots of errors like this:

https://paste.gg/p/anonymous/9164059e151f4177a8b1a44d12a85464/files/31d4687b30e74775a48d73ad998c51c6/raw
The error is always the same:
**java.lang.UnsupportedOperationException: Parsing not implemented (remember to override parse method)**

Almost every skript I made now shows such an error in the console. It only happens when your plugin is installed. 

Some server information:

- [09:41:03] [Server thread/INFO]: This server is running Tuinity version git-Tuinity-"f0e91a4" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
- [Skript] Loading Skript v2.5.3

Let me know if you need more information.

**Comment by milkyskies** [comment]
Just implement parse function as return null in CustomClasses.java c:
